export enum CohortThunkType {
    listCohortUsersCount = 'cohorts/listCohortUsersCount',
    listCohortsUsersCount = 'cohorts/listCohortsUsersCount',
    initiateCampaign = 'cohorts/initiateCampaign',
    listUsers = 'cohorts/listUsers',
    listCohorts = 'cohorts/listCohorts',
    createCohort = 'cohorts/createCohort',
    listCampaigns = 'cohorts/listCampaigns',
    getCampaign = 'cohorts/getCampaign',
    getStats = 'cohorts/getStats',
    bulkAddCohortUsers = 'cohorts/bulkAddCohortUsers',
    bulkReplaceCohortUsers = 'cohorts/bulkReplaceCohortUsers',
    createCohortPushNotification = 'cohorts/createCohortPushNotification',
    createCustomPushNotification = 'cohorts/createCustomPushNotification',
}
