name: Deploy Daakiya-Service Go APP to Amazon ECS

on:
  push:
    branches:
      - dev
      - release
    paths:
      - "go-app/**"
      - ".github/workflows/go-app.yml"

jobs:
  deploy:
    uses: maqsad-io/github-workflows/.github/workflows/ecs.yml@main
    with:
      path: ./go-app/
      cluster_name: Maqsad-${GITHUB_REF#refs/heads/}
      service_name: daakiya-service
      repository_name: be-cloud-daakiya-go-service
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE: CrossAccountSignin-Tools
