env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - next/core-web-vitals
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  #  indent:
  #    - error
  #    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  curly:
    - error
    - multi-or-nest
    - consistent
  object-curly-spacing:
    - error
    - always
  no-unused-vars:
    - 0
    - vars: all
      args: after-used
      ignoreRestSiblings: false
  react/jsx-uses-react:
    - off
  react/react-in-jsx-scope:
    - off
  no-mixed-spaces-and-tabs:
    - off
    - smart-tabs: true

