name: Deploy CRM-Service to Amazon ECS

on:
  push:
    branches:
      - dev
      - release
    paths:
      - "app/**"
      - ".github/workflows/ecs.yml"

jobs:
  deploy:
    uses: maqsad-io/github-workflows/.github/workflows/ecs.yml@main
    with:
      path: ./app/
      cluster_name: Maqsad-${GITHUB_REF#refs/heads/}
      service_name: crm
      repository_name: be-cloud-crm
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE: CrossAccountSignin-Tools
