export enum CallStatus {
	PENDING = 'PENDING',
	COMPLETED = 'COMPLETED',
	CONNECTED = 'CONNECTED',
	IN_PROGRESS = 'IN_PROGRESS',
	UNKNOWN = 'UNKNOWN',
	HUNG_UP = 'HUNG_UP',
	PICKED_UP = 'PICKED_UP',
	CALL_BACK = 'CALL_BACK',
	
}