export enum InterestStatus {
    INTERESTED = 'INTERESTED',
    MIGHT_BE_INTERESTED = 'MIGHT_BE_INTERESTED',
    CALL_BACK = 'CALL_BACK',
    NOT_INTERESTED = 'NOT_INTERESTED',
    AFFORDABILITY_ISSUE = 'AFFORDABILITY_ISSUE',
    IRRELEVANT = 'IRRELEVANT',
}