{{- $releaseName :=  .Release.Namespace }}
{{- if .Values.cronjob }}
{{- range $name , $v := .Values.cronjob}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{$name}}-pvc-backup-cronjob
  namespace: backup
spec:
  schedule: {{$.Values.cronjobConfigs.schedule | quote}}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{$.Values.cronjobConfigs.serviceAccountName}}
          containers:
          - name: backup-container
            image: ammartaimoori/aws-cli-postgres:v1.0.2  # Use an image with awscli and kubectl
            env:
            - name: PGPASSWORD
              value: {{$v.password | quote}}
            command:
              - "/bin/sh"
              - "-c"
            args:
              - >-
                echo "Starting PostgreSQL backup at $(date)" &&
                pg_dump -h {{$v.service}}.{{ $releaseName }}.svc.cluster.local -U {{$v.username}} {{$v.database}}
                | aws s3 cp - s3://{{$.Values.cronjobConfigs.s3Bucket}}/{{ $releaseName }}/{{$name}}-backup.sql &&
                echo "PostgreSQL backup completed at $(date)"
          restartPolicy: OnFailure
{{- end}}
{{- end}}