{{- $appName :=  include "app.fullname" . }}
{{- $labels :=  include "app.labels" . | nindent 4  }}

{{- range $name, $v := .Values.deployments }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-{{$name}}
  labels:
    {{$labels}}
spec:
  type: {{ $v.service.type }}
  ports:
    - port: {{ $v.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $appName }}-{{$name}}

{{- end }}
