name: Deploy Backend

on:
  push:
    branches:
      - dev
      - release
      
    paths:
      - "app/**"
      - ".github/workflows/ecr-app.yml"



jobs:
  deploy-hydra-admin:
    uses: maqsad-io/github-workflows/.github/workflows/ecr.yml@main
    with:
      path: ./app/
      cluster_name: Maqsad-${GITHUB_REF#refs/heads/}
      service_name: haazir-service
      repository_name: be-cloud-ferozi-service
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE: CrossAccountSignin-Tools
