export enum SocketEvent {
    ASSIGN_TICKET = 'ASSIGN_TICKET',
    ARCHIVE_TICKET = 'ARCHIVE_TICKET',
    SEND_AGENT_MESSAGE = 'SEND_AGENT_MESSAGE',
    UPDATE_TICKET = 'UPDATE_TICKET',
    UPDATE_TICKET_MESSAGE = 'UPDATE_TICKET_MESSAGE',
}
