export enum NotionPropertyTypesEnum {
  RICH_TEXT = 'rich_text',
  NUMBER = 'number',
  SELECT = 'select',
  MULTI_SELECT = 'multi_select',
  STATUS = 'status',
  DATE = 'date',
  FORMULA = 'formula',
  RELATION = 'relation',
  ROLLUP = 'rollup',
  TITLE = 'title',
  PEOPLE = 'people',
  FILES = 'files',
  CHECKBOX = 'checkbox',
  URL = 'url',
  EMAIL = 'email',
  PHONE_NUMBER = 'phone_number',
  CREATED_TIME = 'created_time',
  CREATED_BY = 'created_by',
  LAST_EDITED_TIME = 'last_edited_time',
  LAST_EDITED_BY = 'last_edited_by',
}
