export enum ConfigKeys {
  ENV_NAME = 'ENV_NAME',
  PUBLIC_BUCKET = 'PUBLIC_BUCKET',
  WALLET_SERVICE_URL = 'WALLET_SERVICE_URL',
  USER_POPUP_TABLE = 'USER_POPUP_TABLE',
  EIDI_COHORT_TABLE_NAME = 'EIDI_COHORT_TABLE_NAME',

  EXPERIMENT_TABLE_NAME = 'EXPERIMENT_TABLE_NAME',
  USER_EXPERIMENT_TABLE_NAME = 'USER_EXPERIMENT_TABLE_NAME',
  ADMIN_API_URL = 'ADMIN_API_URL',
  MIXPANEL_SERVICE_URL = 'MIXPANEL_SERVICE_URL',

  JARVIS_URL = 'JARVIS_URL',
  TRINO_USERNAME = 'TRINO_USERNAME',
  TRINO_PASSWORD = 'TRINO_PASSWORD',
  BROKER = 'BROKER',
  CONSUMER_GROUP_ID = 'CONSUMER_GROUP_ID',
  USER_FEROZI_INSERT_BATCH_SIZE = 'USER_FEROZI_INSERT_BATCH_SIZE',
  USER_FEROZI_TOPIC= 'USER_FEROZI_TOPIC',
}

export default () => {
  const keys = Object.keys(ConfigKeys);

  const map = {};
  keys.forEach((key) => {
    map[key] = process.env?.[key];
  });
  return map;
};
