export enum ConfigKeys {
  // Remove these
  CAMPAIGN_BUCKET_TABLE_NAME = 'CAMPAIGN_BUCKET_TABLE_NAME',
  CAMPAIGN_BUCKET_CALL_TABLE_NAME = 'CAMPAIGN_BUCKET_CALL_TABLE_NAME',
  CAMPAIGN_BUCKET_AGENT_ASSIGNMENT_TABLE_NAME = 'CAMPAIGN_BUCKET_AGENT_ASSIGNMENT_TABLE_NAME',
  CALL_LOG_TABLE_NAME = 'CALL_LOG_TABLE_NAME',

  // Keep this?
  AGENT_TABLE_NAME = 'AGENT_TABLE_NAME',

  //  DynamoDB
  COHORT_TABLE_NAME = 'COHORT_TABLE_NAME',
  COHORT_CALL_TABLE_NAME = 'COHORT_CALL_TABLE_NAME',
  COHORT_AGENT_ASSIGNMENT_TABLE_NAME = 'COHORT_AGENT_ASSIGNMENT_TABLE_NAME',
  COHORT_CALL_LOG_TABLE_NAME = 'COHORT_CALL_LOG_TABLE_NAME',
  USER_WHATSAPP_CHAT_TRACKING_TABLE_NAME = 'USER_WHATSAPP_CHAT_TRACKING_TABLE_NAME',
  TICKET_AGENT_ASSIGNMENT_TABLE_NAME = 'TICKET_AGENT_ASSIGNMENT_TABLE_NAME',
  TICKET_TABLE_NAME = 'TICKET_TABLE_NAME',
  TICKET_MESSAGE_TABLE_NAME = 'TICKET_MESSAGE_TABLE_NAME',

  //  Meta
  META_API_BASE_URL = 'META_API_BASE_URL',
  WHATSAPP_API_URL = 'WHATSAPP_API_URL',
  WHATSAPP_BEARER_TOKEN = 'WHATSAPP_BEARER_TOKEN',

  // S3
  S3_BUCKET_SAARIF = 'S3_BUCKET_SAARIF',
  S3_BUCKET_SAARIF_URL = 'S3_BUCKET_SAARIF_URL',

  // Kafka
  BROKER_URL = 'BROKER',
  CONSUMER_GROUP_ID = 'CONSUMER_GROUP_ID',

  // Notion
  NOTION_SECRET_KEY = 'NOTION_SECRET_KEY',
  NOTION_COMPLAINT_TRACKER_DATABASE_ID = 'NOTION_COMPLAINT_TRACKER_DATABASE_ID',

  // Slack
  SLACK_USER_OAUTH_TOKEN = 'SLACK_USER_OAUTH_TOKEN',
  SLACK_BOT_OAUTH_TOKEN = 'SLACK_BOT_OAUTH_TOKEN',

  // OTP
  GAJNI_BASE_URL = 'GAJNI_BASE_URL',
  GAJNI_API_KEY = 'GAJNI_API_KEY',

  // Admin Interface
  ADMIN_API_URL = 'ADMIN_API_URL',

  // Database MySQL
  DATABASE_URL = 'DATABASE_URL',

  ENV_NAME = 'ENV_NAME',
}

export default () => {
  const map = Object.fromEntries(
    Object.keys(ConfigKeys).map((key) => [key, process.env?.[key]]),
  );

  console.log('ALL ENVs', JSON.stringify(map));

  return map;
};
